version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg_todolist
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_todolist
    ports:
      - "8080:8080"

volumes:
  pgdata:
